os:
  - linux
sudo: false
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid
before_script:
  - git clone https://github.com/flutter/flutter.git -b beta --depth 1
  - ./flutter/bin/flutter doctor
  - gem install coveralls-lcov
matrix:
  # This causes the build to complete immediately upon first failure or once
  # required jobs are green.
  # @see https://medium.com/@yegorj/building-flutter-apks-and-ipas-on-travis-98d84d8e9b4
  fast_finish: true

  include:
  - name: Test
    env: COMMAND=test --coverage
  #- name: Analyze
  #  env: COMMAND=analyze
script:
  #- cd flight_list
  - ./flutter/bin/flutter $COMMAND
after_success:
  - coveralls-lcov coverage/lcov.info
cache:
  directories:
    - $HOME/.pub-cache